name: Create envfile

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          REACT_APP_MY_NEW_CUSTOM_SECRET_ENV_NAME: ${{ secrets.MY_NEW_CUSTOM_SECRET_ENV_NAME }}
        run: npm run build