jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        env:
          MY_SECRET: ${{ secrets.MY_NEW_CUSTOM_SECRET_ENV_NAME }}
        run: |
          # Use the environment variable in your deployment script or pass it to your application
          echo "Using secret in deployment script"
          # Example: Passing secret to an application command
          npm run deploy --secret=$MY_SECRET
